name: CMake Build Matrix

on: 
  push:
    branches:
      - avrdude

jobs:
  build:
    runs-on: ${ { matrix.os } }
    strategy: 
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - name: Environment
      run: |
      && echo  ${ { matrix.os } }
    - name: Get Avrdude repo
      uses: actions/checkout@v2
      with:
        name: arduino/avrdude-build-script
        ref: refs/heads/release
